# .travis.yml: Travis CI configuration
# Builds at: https://travis-ci.org/vlvrd/yocto-build

dist: bionic
os: linux
sudo: required

vm:
  size: 2x-large

language: python
python:
  - "3.8"

cache:
  directories:
    - poky/build/download
    - poky/build/sstate

env:
  global:
    - YOCTO_TIMEOUT=21600

before_install:
  - cd $TRAVIS_BUILD_DIR/tools/
  - sudo ./setup.sh

script:
  - cd $TRAVIS_BUILD_DIR
  - source oe-init-build-env .
  - (bitbake core-image-minimal) & sleep $YOCTO_TIMEOUT ; kill -INT $!

git:
  depth: 3
#notifications:
#  email: false
